apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: conotoso-3
  labels:
    app.kubernetes.io/name: conotoso-3
    app.kubernetes.io/part-of: conotoso-3-project
    kubernetes.azure.com/generator: devhub
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: conotoso-3