apiVersion: v1
kind: Service
metadata:
  name: contoso-air-2
  namespace: dev
  labels:
    app.kubernetes.io/name: contoso-air-2
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: contoso-air-2
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80